Repository AyushSarode/SignUpButtons.io, pull requests merged in 2022-10, with the labels that each got.

#7 Added Icons to the Buttons
  Social Media Button.html
  icons/facebook.svg
  icons/google.svg
  icons/instagram.svg
  icons/twitter.svg
  icons/youtube.svg
Labels: good first issue, hacktoberfest, hacktoberfest-accepted

#14 Update Social-Media-Button.html
  Social-Media-Button.html
Labels: enhancement, hacktoberfest, hacktoberfest-accepted, hacktoberfest2022

#19 Add Contributors Section in README file
  README.md
Labels: hacktoberfest, hacktoberfest-accepted

#26 Changed styling for icons in mobile view
  index.html
Labels: enhancement, hacktoberfest, hacktoberfest-accepted

#27 changed hover color
  index.html
Labels: hacktoberfest, hacktoberfest-accepted

#29 Added LinkedIn and GitHub Icons to the project
  icons/github.svg
  icons/linkedin.svg
  index.html
Labels: hacktoberfest-accepted
